name = "Accounting"
uuid = "fba18957-09fc-4a37-ab4d-464a4515c58b"
authors = ["Alec Loudenback"]
version = "0.1.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
